version: 2.1

parameters:
  GHA_Action:
    type: string
    default: ""


jobs:
  publish-package:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run:
          name: publish-package
          command: .circleci/publish_package.sh

workflows:
  version: 2
  ci_build:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - publish-package  