version: 2.1

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

workflows:
  ci_build:
    jobs:
      - publish-package:
          context: Global
          filters:
            tags:
              only: /^[0-9].*/

jobs:
  publish-package:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run:
          name: echo
          command: echo "This is pipeline event << pipeline.parameters.GHA_Event  >>"
      - run:
          name: publish-package
          command: .circleci/publish_package.sh
