version: 2.1

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""


jobs:
  publish-package:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run:
          name: echo
          command: echo "This is pipeline event << pipeline.parameters.GHA_Event  >>"
      - run:
          name: publish-package
          command: .circleci/publish_package.sh

workflows:
  ci_build:
    when:
      equal: [ "release", << pipeline.parameters.GHA_Event >> ]
    
    jobs:
      - publish-package:
          context: Global